# Reduce logging level to make sure the application works with SAM local
# https://github.com/aws/serverless-java-container/issues/134
logging.level.root=WARN

spring.application.name=sap_lambda_imageUpload

server.port=8090
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# For local development, you can use the H2 database. For production, you can switch to a different database by changing the properties below.
#spring.datasource.url=jdbc:h2:file:./tmp/testdb;DB_CLOSE_DELAY=-1;TRACE_LEVEL_FILE=0
#For production, you can use a different database by changing the properties below.
spring.datasource.url=jdbc:h2:file:/tmp/testdb;DB_CLOSE_DELAY=-1;TRACE_LEVEL_FILE=0;
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=none
# Enables the web console to view your data at http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# SQL Initialization (Disable for Local Development, Enable for AWS Lambda)
spring.sql.init.mode=never
#To create Schema and Tables on application startup, you can use the following properties:
spring.sql.init.schema-locations=classpath:schema.sql,classpath:Tables.sql
spring.jpa.properties.hibernate.default_schema=SAP_IMAGE
#To enable SQL logging for debugging purposes, you can add the following properties:
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.datasource.hikari.data-source-properties.useClientInfo=false

#********************************************************

# If you want to use this application.properties file for AWS Lambda,
# you can set the SPRING_PROFILES_ACTIVE environment variable to "prod" in your Lambda function configuration.
# This will enable the production profile and use the appropriate database settings for AWS Lambda.

# OR
# if you want to application.properties file for aws lambda, modify the spring.sql.init.mode property to "always" and spring.datasource.url as follows:
# SQL Initialization (Enable for AWS Lambda)
#spring.sql.init.mode=always
#spring.datasource.url=jdbc:h2:file:/tmp/testdb;DB_CLOSE_DELAY=-1;TRACE_LEVEL_FILE=0;INIT=CREATE SCHEMA IF NOT EXISTS SAP_IMAGE
#********************************************************