CREATE TABLE IF NOT EXISTS SAP_IMAGE.IMAGE_STORE (
                                       ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       FILE_CATEGORY VARCHAR(255) NOT NULL,
                                       FILE_NAME VARCHAR(255) NOT NULL,
                                       FILE_TYPE VARCHAR(255) NOT NULL,
                                       IMAGE_DATA BLOB NOT NULL,
                                       UPLOADED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);